"""CLI: build region/object/APK training labels from synthetic payload labels."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, List, Optional

from android_packer.labeling import build_training_labels
from android_packer.utils.jsonl import read_jsonl, write_jsonl


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Align synthetic payload labels to region metadata."
    )
    parser.add_argument(
        "--regions",
        type=Path,
        required=True,
        help="Region metadata JSONL generated by extract-regions.",
    )
    parser.add_argument(
        "--synthetic-labels",
        type=Path,
        nargs="+",
        required=True,
        help="One or more synthetic label JSONL files.",
    )
    parser.add_argument(
        "--region-labels-out",
        type=Path,
        default=Path("data/processed/labels/region_labels.jsonl"),
    )
    parser.add_argument(
        "--object-labels-out",
        type=Path,
        default=Path("data/processed/labels/object_labels.jsonl"),
    )
    parser.add_argument(
        "--apk-labels-out",
        type=Path,
        default=Path("data/processed/labels/apk_labels.jsonl"),
    )
    parser.add_argument(
        "--min-overlap-bytes",
        type=int,
        default=1,
        help="Minimum region/payload byte overlap for a positive region label.",
    )
    parser.add_argument(
        "--min-overlap-ratio",
        type=float,
        default=0.0,
        help="Minimum overlap_bytes / region_size for a positive region label.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    labels = build_training_labels(
        regions=read_jsonl(args.regions),
        synthetic_labels=_read_many_jsonl(args.synthetic_labels),
        min_overlap_bytes=args.min_overlap_bytes,
        min_overlap_ratio=args.min_overlap_ratio,
    )

    region_count = write_jsonl(
        args.region_labels_out,
        (row.to_dict() for row in labels.region_labels),
    )
    object_count = write_jsonl(
        args.object_labels_out,
        (row.to_dict() for row in labels.object_labels),
    )
    apk_count = write_jsonl(
        args.apk_labels_out,
        (row.to_dict() for row in labels.apk_labels),
    )
    positive_regions = sum(row.label_id for row in labels.region_labels)
    positive_objects = sum(row.label_id for row in labels.object_labels)
    positive_apks = sum(row.label_id for row in labels.apk_labels)

    print(
        " ".join(
            [
                f"region_labels={region_count}",
                f"positive_regions={positive_regions}",
                f"object_labels={object_count}",
                f"positive_objects={positive_objects}",
                f"apk_labels={apk_count}",
                f"positive_apks={positive_apks}",
            ]
        )
    )
    return 0


def _read_many_jsonl(paths: Iterable[Path]) -> Iterable[dict]:
    for path in paths:
        yield from read_jsonl(path)


if __name__ == "__main__":
    raise SystemExit(main())
